-- 1) Add status column to creatures (default ACTIVE for existing records)
ALTER TABLE creatures
ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE creatures
ADD CONSTRAINT chk_creatures_status
CHECK (status IN ('ACTIVE', 'REMOVED'));

-- 2) Create users table
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(120)                            NOT NULL,
    email      VARCHAR(120)                            NOT NULL UNIQUE,
    phone      VARCHAR(30),
    role       VARCHAR(30)                             NOT NULL DEFAULT 'STAFF',
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
ADD CONSTRAINT chk_users_role
CHECK (role IN ('ADMIN', 'STAFF', 'VET', 'RESEARCHER'));

-- 3) Create observations table
CREATE TABLE observations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creature_id BIGINT                                  NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    notes       TEXT                                    NOT NULL,
    observed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_observations PRIMARY KEY (id),
    CONSTRAINT fk_observations_creature FOREIGN KEY (creature_id) REFERENCES creatures (id),
    CONSTRAINT fk_observations_author   FOREIGN KEY (author_id)   REFERENCES users (id)
);

-- 4) Create feeding_schedules table
CREATE TABLE feeding_schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creature_id BIGINT                                  NOT NULL,
    feed_time   TIME                                    NOT NULL,
    food_type   VARCHAR(120)                            NOT NULL,
    notes       TEXT,
    CONSTRAINT pk_feeding_schedules PRIMARY KEY (id),
    CONSTRAINT fk_feeding_creature FOREIGN KEY (creature_id) REFERENCES creatures (id)
);
